-- Approval-lock foundation: tony_pending_approvals + tony_action_grants
--   + tony_approval_devices + the immutability/state-machine trigger
--
-- First code-layer brick of the governor narrow-fix. Implements:
--   - the lock DESIGN (nova-docs commit 10fbf07, SOUND across 5 Codex rounds)
--   - the alpha auth contract (nova-docs commit f0adcde, ARCHITECTURE SOUND
--     across 2 Codex rounds — backend-trusted shared-secret model)
--
-- SCOPE — this brick:
--   - 3 tables (alpha §1, alpha §2, lock-design §3 simplified per alpha §3)
--   - 1 BEFORE INSERT OR UPDATE trigger on tony_pending_approvals enforcing
--     immutability + state machine + write-once monotonicity + per-status
--     companion consistency (alpha §2 with alpha-r2 fixes #1, #2, #6)
--   - matching init function: app/core/approval_lock.py::init_approval_lock_tables()
--     wired into _inits in app/api/v1/router.py (AGENTS.md:32 convention)
--
-- NOT in this brick (later bricks):
--   - approve/deny/list endpoints (alpha §4-§6)
--   - the verify_and_consume gate at governor.py:215 (lock-design §5)
--   - mint logic (atomic approve_pending function)
--   - all of the implementation brief's other items
--
-- [KNOWN GAP] Uses CREATE TABLE IF NOT EXISTS per AGENTS.md:32 convention.
-- The schema-drift hazard (`2026-06-05-schema-drift-audit.md`) applies to
-- FUTURE column additions to these tables. First-deploy creation EXPECTS
-- prod to have none of these tables yet (the brick that introduces them)
-- and EXPECTS no partial prior init / manual table — IF NOT EXISTS will
-- silently accept any wrong-schema pre-existing same-named table, so the
-- precondition is asserted by deploy review, not by the migration itself.
-- Future column additions to these security-critical tables MUST go
-- through a versioned migration with explicit drift validation, not
-- in-place CREATE TABLE IF NOT EXISTS edits in the init function. The
-- wider project-wide drift reconciliation is its own backlog item per
-- the schema-drift audit. Closes Codex brick-1 review #4.
--
-- This file is wrapped in BEGIN; ... COMMIT; so that direct
-- `psql -f` application (e.g. the restore-drill workflow) is atomic. The
-- paired init function `app/core/approval_lock.py::init_approval_lock_tables`
-- does the same wrapping in Python via `conn.autocommit = False` +
-- explicit `commit()`. The DROP TRIGGER IF EXISTS / CREATE TRIGGER pair
-- and the ALTER TABLE DROP / ADD CONSTRAINT pair MUST be atomic to avoid
-- a fail-open window where the trigger or FK is absent (Codex brick-1
-- review #1).

BEGIN;
--
-- Cross-references:
--   nova-docs/2026-06-05-governor-narrow-fix-design.md          (lock design, SOUND, 10fbf07)
--   nova-docs/2026-06-06-approval-auth-alpha-design.md          (alpha auth, sound architecture, f0adcde)
--   nova-docs/2026-06-05-governor-narrow-fix-implementation-brief.md  (brief, parked, 046a616)
--   nova-docs/2026-06-05-schema-drift-audit.md                  (drift hazard)


-- =============================================================================
-- §1  tony_approval_devices  (alpha §1)
-- =============================================================================
-- Per-device enrolment record. Stores SHA-256 of the per-device secret
-- (NEVER the raw secret). The raw secret is generated by the device, never
-- transmitted to the backend except inside the X-Approval-Secret header on
-- approve/deny/list, and never logged (alpha §9 redaction layers).

CREATE TABLE IF NOT EXISTS tony_approval_devices (
    device_id       UUID PRIMARY KEY,
    device_name     TEXT NOT NULL,
    -- secret_hash is SHA-256 of the decoded 32 raw bytes of the device's
    -- secret (NOT of the base64url wire representation; see alpha §7 and §9).
    -- Pinned to exactly 64 lowercase hex characters (alpha-r2 #4).
    secret_hash     TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at      TIMESTAMPTZ,
    last_seen_at    TIMESTAMPTZ,
    CHECK (status IN ('active', 'revoked')),
    CHECK (secret_hash ~ '^[0-9a-f]{64}$'),
    -- Companion-consistency on the device row itself: an active device has
    -- no revoked_at; a revoked device has one. Mirrors the pending-row
    -- companion-consistency pattern at a smaller scale.
    CHECK ((status = 'active'  AND revoked_at IS NULL)
        OR (status = 'revoked' AND revoked_at IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_tony_approval_devices_active
    ON tony_approval_devices(status)
    WHERE status = 'active';


-- =============================================================================
-- §2  tony_pending_approvals  (alpha §2 + lock design §4)
-- =============================================================================
-- A destructive action awaiting Matthew's approval via an enrolled device.
-- Created by the chat/agent pipeline when a registry-destructive capability
-- is requested. Approved or denied by the (later) approval endpoints. On
-- successful approve, a grant row is minted in tony_action_grants and the
-- pending row's status + grant_id + approved_at + approved_by_device_id +
-- approval_challenge_used_at are set together in ONE atomic UPDATE.
--
-- The BEFORE INSERT OR UPDATE trigger tony_pending_approvals_guard (defined
-- below in §4) enforces every invariant the alpha design promises:
--   - immutable fields after creation (on UPDATE)
--   - state machine: awaiting -> {approved, denied, expired} only
--   - write-once monotonicity on companion fields (on UPDATE)
--   - per-status companion consistency (on INSERT AND UPDATE)
-- It MUST permit the all-at-once approve transition (alpha-r2 #1): an UPDATE
-- from awaiting (companions NULL) to approved (status + grant_id + used_at +
-- approved_by_device_id + approved_at all set in one statement) MUST succeed.

CREATE TABLE IF NOT EXISTS tony_pending_approvals (
    pending_id                  UUID PRIMARY KEY,
    capability_key              TEXT NOT NULL,
    -- action_hash is SHA-256 of the canonical ValidatedAction (lock design §1
    -- + §2), stored as raw 32 bytes. Wire form is lowercase hex (alpha §3);
    -- BYTEA is the DB-side authoritative representation.
    action_hash                 BYTEA NOT NULL,
    -- action_snapshot is the canonical-JSON serialisation of the deep-frozen
    -- ValidatedAction. Shown to the approver in the app's pending-list UI
    -- so they see exactly what executes, byte-for-byte.
    action_snapshot             JSONB NOT NULL,
    status                      TEXT NOT NULL DEFAULT 'awaiting',
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at                  TIMESTAMPTZ NOT NULL,
    -- approval_challenge is a 128-bit CSPRNG nonce. Single-use via
    -- approval_challenge_used_at (set during the atomic approve/deny UPDATE).
    approval_challenge          BYTEA NOT NULL,
    approval_challenge_used_at  TIMESTAMPTZ,
    approved_by_device_id       UUID REFERENCES tony_approval_devices(device_id),
    approved_at                 TIMESTAMPTZ,
    denied_by_device_id         UUID REFERENCES tony_approval_devices(device_id),
    denied_at                   TIMESTAMPTZ,
    -- grant_id logically references tony_action_grants(grant_id) but the FK
    -- is added at the end of this file via ALTER TABLE so the create order
    -- of the two tables does not require a forward declaration. See §3.
    grant_id                    UUID,
    CHECK (status IN ('awaiting', 'approved', 'denied', 'expired')),
    CHECK (octet_length(action_hash) = 32),        -- SHA-256 raw is 32 bytes
    CHECK (octet_length(approval_challenge) >= 16),-- 128-bit minimum
    CHECK (expires_at > created_at)
);

-- Hot-path index: the gate's most common read is "find awaiting pendings,
-- ordered by expiry" (for cleanup + lookup). Partial index keeps it small.
CREATE INDEX IF NOT EXISTS idx_tony_pending_approvals_awaiting
    ON tony_pending_approvals(expires_at)
    WHERE status = 'awaiting';


-- =============================================================================
-- §3  tony_action_grants  (lock-design §3 + alpha §3 simplification)
-- =============================================================================
-- A one-time-use authorization bound to a specific ValidatedAction (via
-- action_hash) and to its originating pending_approval (via pending_action_ref
-- UNIQUE). Minted ONLY by the later approve_pending handler on successful
-- Matthew-authn'd approval. Consumed by the later verify_and_consume at the
-- gate (lock-design §5).

CREATE TABLE IF NOT EXISTS tony_action_grants (
    grant_id            UUID PRIMARY KEY,
    capability_key      TEXT NOT NULL,
    -- Copied STRICTLY from the LOCKED pending row's action_hash at mint
    -- time (alpha §4 step 10 + lock-design Codex r1 #4). Never from client.
    action_hash         BYTEA NOT NULL,
    -- UNIQUE backstop: one pending -> at most one grant. Closes the original
    -- Codex r1 #4 finding on the lock design.
    pending_action_ref  UUID NOT NULL UNIQUE
                        REFERENCES tony_pending_approvals(pending_id),
    -- Narrow-fix scope: human approval is the only mint path. The broader
    -- effect-mediator brick (deferred) introduces additional minted_by values.
    minted_by           TEXT NOT NULL DEFAULT 'human_approval',
    minted_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at          TIMESTAMPTZ NOT NULL,
    consumed_at         TIMESTAMPTZ,
    status              TEXT NOT NULL DEFAULT 'active',
    CHECK (status IN ('active', 'consumed', 'expired', 'denied')),
    CHECK (minted_by = 'human_approval'),
    CHECK (octet_length(action_hash) = 32),
    CHECK (expires_at > minted_at),
    CHECK (
        (status = 'consumed' AND consumed_at IS NOT NULL)
        OR (status <> 'consumed' AND consumed_at IS NULL)
    )
);

-- Hot-path index: verify_and_consume's CAS narrows by (capability_key,
-- action_hash) on active grants.
CREATE INDEX IF NOT EXISTS idx_tony_action_grants_active_by_action
    ON tony_action_grants(capability_key, action_hash)
    WHERE status = 'active';

-- Now that tony_action_grants exists, install the FK constraint on
-- tony_pending_approvals.grant_id. Idempotent via DROP IF EXISTS + ADD.
ALTER TABLE tony_pending_approvals
    DROP CONSTRAINT IF EXISTS tony_pending_approvals_grant_fk;
ALTER TABLE tony_pending_approvals
    ADD CONSTRAINT tony_pending_approvals_grant_fk
    FOREIGN KEY (grant_id) REFERENCES tony_action_grants(grant_id);


-- =============================================================================
-- §4  Trigger: tony_pending_approvals_guard  (alpha §2 with r2 #1, #2, #6 fixes)
-- =============================================================================
-- The load-bearing piece of this brick. Enforces every invariant the alpha
-- design promises, on BOTH INSERT and UPDATE so malformed initial inserts are
-- rejected just as malformed updates are (closes alpha-r1 #3).
--
-- INVARIANTS (each with a unique RAISE EXCEPTION message so test SQL can
-- detect *which* rule fired):
--
--   IMMUTABILITY (UPDATE only) — these fields are set at INSERT and frozen:
--     pending_id, capability_key, action_hash, action_snapshot,
--     approval_challenge, created_at, expires_at
--
--   STATE MACHINE (UPDATE only):
--     status may transition awaiting -> {approved, denied, expired} ONLY.
--     No reverse, no approved<->denied, no expired<->anything.
--
--   WRITE-ONCE MONOTONICITY (UPDATE only — INSERT may set fresh values):
--     approved_at, denied_at, approved_by_device_id, denied_by_device_id,
--     approval_challenge_used_at, grant_id. Once any is non-NULL, it cannot
--     change to a different value and cannot be cleared back to NULL.
--
--   COMPANION CONSISTENCY (INSERT AND UPDATE — per status):
--     awaiting requires ALL companion fields NULL
--     approved requires approved_at + approved_by_device_id +
--              approval_challenge_used_at + grant_id NON-NULL;
--              denied_at + denied_by_device_id NULL
--     denied   requires denied_at + denied_by_device_id +
--              approval_challenge_used_at NON-NULL;
--              approved_at + approved_by_device_id + grant_id NULL
--     expired  requires ALL companion fields NULL, INCLUDING
--              approval_challenge_used_at (alpha-r2 #6 tightened)
--
-- ALL-AT-ONCE APPROVE TRANSITION (alpha-r2 #1):
--     An UPDATE from awaiting (companions NULL) to approved (status +
--     grant_id + approval_challenge_used_at + approved_by_device_id +
--     approved_at all set in ONE statement) MUST succeed. The
--     companion-consistency check above examines NEW values only; if the
--     post-UPDATE row satisfies the approved invariant in one shot, the
--     trigger passes. The trigger does NOT require an intermediate state.

CREATE OR REPLACE FUNCTION tony_pending_approvals_guard() RETURNS TRIGGER AS $$
BEGIN
    -- =====================================================================
    -- IMMUTABILITY (UPDATE only)
    -- =====================================================================
    IF TG_OP = 'UPDATE' THEN
        IF NEW.pending_id IS DISTINCT FROM OLD.pending_id THEN
            RAISE EXCEPTION 'tony_pending_approvals: pending_id is immutable';
        END IF;
        IF NEW.capability_key IS DISTINCT FROM OLD.capability_key THEN
            RAISE EXCEPTION 'tony_pending_approvals: capability_key is immutable';
        END IF;
        IF NEW.action_hash IS DISTINCT FROM OLD.action_hash THEN
            RAISE EXCEPTION 'tony_pending_approvals: action_hash is immutable';
        END IF;
        IF NEW.action_snapshot IS DISTINCT FROM OLD.action_snapshot THEN
            RAISE EXCEPTION 'tony_pending_approvals: action_snapshot is immutable';
        END IF;
        IF NEW.approval_challenge IS DISTINCT FROM OLD.approval_challenge THEN
            RAISE EXCEPTION 'tony_pending_approvals: approval_challenge is immutable';
        END IF;
        IF NEW.created_at IS DISTINCT FROM OLD.created_at THEN
            RAISE EXCEPTION 'tony_pending_approvals: created_at is immutable';
        END IF;
        IF NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
            RAISE EXCEPTION 'tony_pending_approvals: expires_at is immutable';
        END IF;
    END IF;

    -- =====================================================================
    -- STATE MACHINE (UPDATE only)
    -- =====================================================================
    IF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
        IF NOT (OLD.status = 'awaiting'
                AND NEW.status IN ('approved', 'denied', 'expired')) THEN
            RAISE EXCEPTION 'tony_pending_approvals: invalid status transition % -> %',
                OLD.status, NEW.status;
        END IF;
    END IF;

    -- =====================================================================
    -- WRITE-ONCE MONOTONICITY (UPDATE only — INSERT may set fresh values)
    -- =====================================================================
    IF TG_OP = 'UPDATE' THEN
        IF OLD.approved_at IS NOT NULL
           AND NEW.approved_at IS DISTINCT FROM OLD.approved_at THEN
            RAISE EXCEPTION 'tony_pending_approvals: approved_at is write-once';
        END IF;
        IF OLD.denied_at IS NOT NULL
           AND NEW.denied_at IS DISTINCT FROM OLD.denied_at THEN
            RAISE EXCEPTION 'tony_pending_approvals: denied_at is write-once';
        END IF;
        IF OLD.approved_by_device_id IS NOT NULL
           AND NEW.approved_by_device_id IS DISTINCT FROM OLD.approved_by_device_id THEN
            RAISE EXCEPTION 'tony_pending_approvals: approved_by_device_id is write-once';
        END IF;
        IF OLD.denied_by_device_id IS NOT NULL
           AND NEW.denied_by_device_id IS DISTINCT FROM OLD.denied_by_device_id THEN
            RAISE EXCEPTION 'tony_pending_approvals: denied_by_device_id is write-once';
        END IF;
        IF OLD.approval_challenge_used_at IS NOT NULL
           AND NEW.approval_challenge_used_at IS DISTINCT FROM OLD.approval_challenge_used_at THEN
            RAISE EXCEPTION 'tony_pending_approvals: approval_challenge_used_at is write-once';
        END IF;
        IF OLD.grant_id IS NOT NULL
           AND NEW.grant_id IS DISTINCT FROM OLD.grant_id THEN
            RAISE EXCEPTION 'tony_pending_approvals: grant_id is write-once';
        END IF;
    END IF;

    -- =====================================================================
    -- COMPANION CONSISTENCY (INSERT AND UPDATE — per-status invariants)
    -- =====================================================================
    IF NEW.status = 'awaiting' THEN
        IF NEW.approved_at IS NOT NULL
           OR NEW.approved_by_device_id IS NOT NULL
           OR NEW.denied_at IS NOT NULL
           OR NEW.denied_by_device_id IS NOT NULL
           OR NEW.approval_challenge_used_at IS NOT NULL
           OR NEW.grant_id IS NOT NULL THEN
            RAISE EXCEPTION 'tony_pending_approvals: status=awaiting requires all companion fields NULL';
        END IF;
    ELSIF NEW.status = 'approved' THEN
        IF NEW.approved_at IS NULL
           OR NEW.approved_by_device_id IS NULL
           OR NEW.approval_challenge_used_at IS NULL
           OR NEW.grant_id IS NULL THEN
            RAISE EXCEPTION 'tony_pending_approvals: status=approved requires approved_at + approved_by_device_id + approval_challenge_used_at + grant_id all NON-NULL';
        END IF;
        IF NEW.denied_at IS NOT NULL OR NEW.denied_by_device_id IS NOT NULL THEN
            RAISE EXCEPTION 'tony_pending_approvals: status=approved requires denied_at and denied_by_device_id NULL';
        END IF;
    ELSIF NEW.status = 'denied' THEN
        IF NEW.denied_at IS NULL
           OR NEW.denied_by_device_id IS NULL
           OR NEW.approval_challenge_used_at IS NULL THEN
            RAISE EXCEPTION 'tony_pending_approvals: status=denied requires denied_at + denied_by_device_id + approval_challenge_used_at all NON-NULL';
        END IF;
        IF NEW.approved_at IS NOT NULL
           OR NEW.approved_by_device_id IS NOT NULL
           OR NEW.grant_id IS NOT NULL THEN
            RAISE EXCEPTION 'tony_pending_approvals: status=denied requires approved_at, approved_by_device_id, grant_id all NULL';
        END IF;
    ELSIF NEW.status = 'expired' THEN
        -- alpha-r2 #6: tightened. expired requires approval_challenge_used_at
        -- to be NULL too; the lock-first design guarantees a losing consume
        -- attempt rolls back its used_at update, so a valid path never
        -- produces (expired, used_at IS NOT NULL).
        IF NEW.approved_at IS NOT NULL
           OR NEW.approved_by_device_id IS NOT NULL
           OR NEW.denied_at IS NOT NULL
           OR NEW.denied_by_device_id IS NOT NULL
           OR NEW.grant_id IS NOT NULL
           OR NEW.approval_challenge_used_at IS NOT NULL THEN
            RAISE EXCEPTION 'tony_pending_approvals: status=expired requires all companion fields NULL (including approval_challenge_used_at, alpha-r2 #6)';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Idempotent trigger install.
DROP TRIGGER IF EXISTS tony_pending_approvals_guard_trigger
    ON tony_pending_approvals;
CREATE TRIGGER tony_pending_approvals_guard_trigger
    BEFORE INSERT OR UPDATE ON tony_pending_approvals
    FOR EACH ROW EXECUTE FUNCTION tony_pending_approvals_guard();

COMMIT;
